### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly_idle#2]
- [ ] Add unit tests
- [ ] Setup pre-commit
- [ ] Test with all Python versions
- [x] Upload to PyPI

**Comment by aroberge** [comment]
Closing this issue as being no longer relevant - however, unit tests might be useful to have if I could figure out how to do them.
